import{a as L,S as w,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))g(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&g(l)}).observe(document,{childList:!0,subtree:!0});function f(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function g(t){if(t.ep)return;t.ep=!0;const r=f(t);fetch(t.href,r)}})();const b="https://pixabay.com/api/",v="53391226-a2ec73fe425479568eec525bb";async function P(e,o=1){return(await L.get(b,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o}})).data}const m=document.querySelector(".gallery"),n=document.querySelector(".js-load-btn");let i=null;function S(){i||(i=new w(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,docClose:!1}))}function E(){i&&i.refresh()}function q(e){return`<li class='gallery-item'>
    <a class='gallery-link' href=${e.largeImageURL}>
    <img loading='lazy' class='gallery-image' src='${e.webformatURL}' alt='${e.tags}'/>
    <div class='img'>
    <p><strong>Likes</strong> ${e.likes}</p>
    <p><strong>Views</strong> ${e.views}</p>
    <p><strong>Comments</strong> ${e.comments}</p>
    <p><strong>Downloads</strong> ${e.downloads}</p></div></a></li>`}function I(e){const o=e.map(q).join("");m.insertAdjacentHTML("beforeend",o),E()}function x(){m.innerHTML=""}function h(){const e=document.getElementById("loader-overlay");e&&(e==null||e.classList.remove("hidden"))}function u(){const e=document.getElementById("loader-overlay");e&&(e==null||e.classList.add("hidden"))}function D(){n&&(n==null||n.classList.remove("hidden"))}function c(){n&&(n==null||n.classList.add("hidden"))}const $=document.querySelector(".form"),B=15;let d="",s=1,y=0;c();u();S();$.addEventListener("submit",async e=>{if(e.preventDefault(),d=new FormData(e.target).get("search-text").trim(),s=1,!d){a.warning({title:"Warning",message:"Please enter a search term!"});return}x(),c(),h(),await p()});n.addEventListener("click",async()=>{s+=1,c(),h(),await p()});async function p(){try{const e=await P(d,s);if(e.hits.length===0&&s===1){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}y=Math.ceil(e.total/B),I(e.hits),M(),s>1&&A()}catch(e){a.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(e)}finally{u()}}function M(){s<y?D():(c(),a.info({title:"The End",message:"We`re sorry, but you`ve reached the end of search results."}))}function A(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
